### ISSUE TITLE
LUKS unattended builds do not complete automatically

### ISSUE THREAD

**Issue by goldyfruit** [tylert/packer-build#31]
Hi guys,

I'm trying to build images with `LUKS` encryption but when the OS reboots it asking for the password to unlock the boot.

I'm using `QEMU` builder with `KVM`  acceleration.

Is there a way to automate this without been in front of the `VNC` console?

Thanks :)

**Comment by tylert** [comment]
That'd be **LUKS**, not LUSK (https://en.wikipedia.org/wiki/Linux_Unified_Key_Setup).

Regrettably, no, last time I checked, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=656710 had not yet made it into the installer versions that were then available for the current versions of Debian and Ubuntu so these debconf settings were being ignored.  I confess that I haven't retested the automated building of FDE images in a while so, perhaps, this has been fixed in Debian Buster and/or Ubuntu Eoan or Fecal.  You didn't mention which images you were testing.

If you feel that you would like to take a shot at fixing this, the pertinent lines in the preseed files look like these https://github.com/tylert/packer-build/blob/master/source/debian/10_buster/base-crypt.preseed#L74-L78 (presumably, someone doing the fix would also do so for all the other preseed files with "crypt" in their names).

NOTE:  Your help with fixing and testing this would be most appreciated.  I have been reluctant to flood this project with a lot of open, stagnant issues while I'm the only active maintainer as I am pessimistic of my ability to close them in a timely manner.

**Comment by tylert** [comment]
Err.  Sorry, my cache was stale.  The preseed stuff works correctly, however, there isn't yet a nice way to tell Packer to type this in at second boot.

**Comment by goldyfruit** [comment]
@tylert thanks for answering.
Yeah, all the preseed is working as expected, good job about that!

I'll look around to see if I'm able to find a solution.

**Comment by goldyfruit** [comment]
One solution seems to load a SSH server into the `initramfs` such as Dropbear. It doesn't seems to be easy but I'll give a shot.

**Comment by tylert** [comment]
Bonne chance.  Merci.

**Comment by opsxcq** [comment]
You can configure `LUKS` to use some file as key, and make this file very predictable, like using some external device with only one file, or `/dev/zero`
